---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-datasource-org
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-datasource-org
    creationPolicy: Owner
  data:
    - secretKey: ORG_ID
      remoteRef:
        key: grafana-datasource-org
        property: org-id
