---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: waypoint
    name: mimir-system
    pod-security.kubernetes.io/enforce: privileged
