---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/keda.sh/scaledobject_v1alpha1.json
# Mimir/Grafana cross-namespace queries traverse this waypoint on ingress.
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: waypoint
spec:
  scaleTargetRef:
    name: waypoint
  minReplicaCount: 3
  maxReplicaCount: 6
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 600
          policies:
            - type: Percent
              value: 50
              periodSeconds: 120
        scaleUp:
          stabilizationWindowSeconds: 120
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
