---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: delilah
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  title: delilah
  uid: delilah
