---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./delilah-alertrules.yaml
  - ./delilah-folder.yaml
  - ./grafanadatasource.yaml
  - ./grafanadatasource-admin-tenants.yaml
  - ./grafana.yaml
  - ./istio-dashboards.yaml
  - ./peerauthentication.yaml
  - ./poddisruptionbudget.yaml
  - ./servicemonitor.yaml

configMapGenerator:
  - name: istio-workload-dashboard
    files:
      - dashboards/istio-workload-dashboard.json
  - name: istio-service-dashboard
    files:
      - dashboards/istio-service-dashboard.json

generatorOptions:
  disableNameSuffixHash: true
