---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: grafana
spec:
  scaleTargetRef:
    name: grafana-deployment
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://mimir.mimir-system.svc.cluster.local:8080/prometheus
        customHeaders: X-Scope-OrgID=witl-xyz
        query: sum(rate(grafana_http_request_duration_seconds_count{job="grafana-service"}[2m]))
        threshold: "50"
