---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  chart:
    spec:
      chart: kyverno
      version: 3.9.0
      sourceRef:
        kind: HelmRepository
        name: kyverno
  interval: 1h
  timeout: 15m
  values:
    admissionController:
      replicas: 3
      container:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 384Mi
      podDisruptionBudget:
        enabled: true
        minAvailable: 2
      serviceMonitor:
        enabled: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: admission-controller
              app.kubernetes.io/instance: kyverno
    backgroundController:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          memory: 128Mi
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      serviceMonitor:
        enabled: true
    cleanupController:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          memory: 128Mi
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      serviceMonitor:
        enabled: true
    reportsController:
      replicas: 2
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          memory: 128Mi
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      serviceMonitor:
        enabled: true
