---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  description: "Kuma service mesh & cloud ops workloads"
  sourceRepos:
    - "*"
  destinations:
    - namespace: kuma-system
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: ""
      kind: "Namespace"
