---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: authentik-server
  namespace: authentik
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentik-server
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: authentik-worker
  namespace: authentik
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentik-worker
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mimir
  namespace: mimir-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mimir
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana-deployment
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grafana-deployment
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-monitoring-alloy-metrics
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: k8s-monitoring-alloy-metrics
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: loki-backend
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: loki-backend
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: loki-read
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loki-read
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: loki-write
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: loki-write
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tempo-distributor
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tempo-distributor
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tempo-ingester
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: tempo-ingester
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tempo-metrics-generator
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tempo-metrics-generator
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tempo-querier
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tempo-querier
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tempo-query-frontend
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tempo-query-frontend
  updatePolicy:
    updateMode: "Off"
