---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
# 1Password item "cnpg-backup": ACCESS_KEY_ID, ACCESS_SECRET_KEY
# 1Password item "authentik-db": password (username is fixed to authentik)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cnpg-backup
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: cnpg-backup
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: cnpg-backup
        property: ACCESS_SECRET_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: authentik
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: authentik-db
        property: password
