---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/pooler_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-pooler-ro
spec:
  cluster:
    name: postgres
  instances: 2
  type: ro
  monitoring:
    enablePodMonitor: false
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-pooler-ro
    spec:
      containers: []
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: postgres-pooler-ro
                topologyKey: kubernetes.io/hostname
