---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - ./namespace.yaml
  - ./istio/ks.yaml
  - ./kiali-operator/ks.yaml
  - ./kiali/secrets/ks.yaml
  - ./kiali/ks.yaml
