---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-monitoring-mimir-org
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: k8s-monitoring-mimir-org
  data:
    - secretKey: tenantId
      remoteRef:
        key: grafana-datasource-org
        property: org-id
