# OAuth2/OIDC and LDAP providers. client_id values are public identifiers; client
# secrets are generated by authentik and never stored here (they stay computed).

locals {
  oidc_scopes = [for s in ["openid", "email", "profile"] : data.authentik_property_mapping_provider_scope.oidc[s].id]
}

resource "authentik_provider_oauth2" "grafana" {
  name                  = "Grafana"
  client_id             = "ccIrxoIFzPkF9CmYHwgLnP6i18B4RS3k0wOOi03N"
  client_type           = "confidential"
  access_token_validity = "hours=1"
  authentication_flow   = authentik_flow.default_authentication_flow.uuid
  authorization_flow    = data.authentik_flow.default_provider_authorization_explicit_consent.id
  invalidation_flow     = data.authentik_flow.default_invalidation_flow.id
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
  grant_types           = ["authorization_code", "refresh_token"]
  sub_mode              = "hashed_user_id"
  property_mappings = concat(local.oidc_scopes, [
    data.authentik_property_mapping_provider_scope.offline_access.id,
    authentik_property_mapping_provider_scope.observability_tenant_id.id,
  ])
  allowed_redirect_uris = [{
    matching_mode     = "strict"
    redirect_uri_type = "authorization"
    url               = "https://grafana.cloud.witl.xyz/login/generic_oauth"
  }]
}

resource "authentik_provider_oauth2" "kiali" {
  name                  = "Kiali"
  client_id             = "GtCB6L8dMsSKlkYYl3TXfs0RQFL62VPVUjf8zmci"
  client_type           = "confidential"
  access_token_validity = "hours=1"
  authentication_flow   = authentik_flow.default_authentication_flow.uuid
  authorization_flow    = data.authentik_flow.default_provider_authorization_explicit_consent.id
  invalidation_flow     = data.authentik_flow.default_invalidation_flow.id
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
  grant_types           = ["authorization_code", "refresh_token"]
  sub_mode              = "user_email"
  property_mappings     = concat(local.oidc_scopes, [data.authentik_property_mapping_provider_scope.offline_access.id])
  allowed_redirect_uris = [{
    matching_mode     = "strict"
    redirect_uri_type = "authorization"
    url               = "https://kiali.cloud.witl.xyz/kiali"
  }]
}

# Not attached to any application (superseded by "Kiali" above). Kept so the import
# is lossless; delete this resource to remove it from authentik.
resource "authentik_provider_oauth2" "provider_for_kiali" {
  name                  = "Provider for Kiali"
  client_id             = "bpk4V5UO6o0tGwp7NQttgEt1OxRHLCh4RTLzXjoC"
  client_type           = "confidential"
  access_token_validity = "hours=1"
  authentication_flow   = authentik_flow.default_authentication_flow.uuid
  authorization_flow    = data.authentik_flow.default_provider_authorization_explicit_consent.id
  invalidation_flow     = data.authentik_flow.default_invalidation_flow.id
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
  grant_types           = ["authorization_code", "refresh_token"]
  sub_mode              = "hashed_user_id"
  property_mappings     = concat(local.oidc_scopes, [data.authentik_property_mapping_provider_scope.offline_access.id])
  allowed_redirect_uris = [{
    matching_mode     = "strict"
    redirect_uri_type = "authorization"
    url               = "https://kiali.cloud.witl.xyz/kiali/oauth/callback"
  }]
}

resource "authentik_provider_oauth2" "grafana_kiali_m2m" {
  name                  = "Grafana Kiali M2M"
  client_id             = "Acwy5OKIVEstosWxsBFrRkQHGsj5vCTMQoFR0PdN"
  client_type           = "confidential"
  access_token_validity = "hours=1"
  authentication_flow   = authentik_flow.default_authentication_flow.uuid
  authorization_flow    = data.authentik_flow.default_provider_authorization_explicit_consent.id
  invalidation_flow     = data.authentik_flow.default_invalidation_flow.id
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
  grant_types           = ["client_credentials"]
  sub_mode              = "hashed_user_id"
  property_mappings     = concat(local.oidc_scopes, [data.authentik_property_mapping_provider_scope.offline_access.id])
}

resource "authentik_provider_oauth2" "observability_m2m" {
  name                  = "Observability M2M"
  client_id             = "k18bomzx3cFczB1qTrpMwMNcvBwbwZ67ywKTGVju"
  client_type           = "confidential"
  access_token_validity = "hours=1"
  authentication_flow   = authentik_flow.default_authentication_flow.uuid
  authorization_flow    = data.authentik_flow.default_provider_authorization_explicit_consent.id
  invalidation_flow     = data.authentik_flow.default_invalidation_flow.id
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
  grant_types           = ["client_credentials"]
  sub_mode              = "hashed_user_id"
  property_mappings = concat(
    [for s in local.observability_scopes : authentik_property_mapping_provider_scope.observability[s].id],
    [
      authentik_property_mapping_provider_scope.observability_tenant_id.id,
      authentik_property_mapping_provider_scope.oauth2_tenant_id_from_service_account_attribute.id,
    ],
  )
}

resource "authentik_provider_oauth2" "hubble" {
  name                  = "hubble"
  client_id             = "zEXboNjNhVgjW3SBnD6ZNAh6BV6ZcpeFQe83i45Y"
  client_type           = "confidential"
  access_token_validity = "hours=1"
  authorization_flow    = data.authentik_flow.default_provider_authorization_implicit_consent.id
  invalidation_flow     = data.authentik_flow.default_invalidation_flow.id
  signing_key           = data.authentik_certificate_key_pair.self_signed.id
  grant_types           = ["authorization_code", "implicit", "refresh_token", "client_credentials"]
  sub_mode              = "user_email"
  property_mappings     = concat(local.oidc_scopes, [authentik_property_mapping_provider_scope.oauth2_groups.id])
  allowed_redirect_uris = [{
    matching_mode     = "strict"
    redirect_uri_type = "authorization"
    url               = "https://hubble.cloud.witl.xyz/callback"
  }]
}

resource "authentik_provider_oauth2" "hermes" {
  name                    = "Provider for Hermes"
  client_id               = "G7uiMQaMKhCq6I5HDseBFkdgfc9lQFc8HNZlm9yu"
  client_type             = "public"
  authorization_flow      = data.authentik_flow.default_provider_authorization_implicit_consent.id
  invalidation_flow       = data.authentik_flow.default_provider_invalidation_flow.id
  signing_key             = data.authentik_certificate_key_pair.self_signed.id
  grant_types             = ["authorization_code", "implicit", "hybrid", "refresh_token", "client_credentials", "password", "urn:ietf:params:oauth:grant-type:device_code"]
  sub_mode                = "hashed_user_id"
  access_token_validity   = "minutes=5"
  refresh_token_threshold = "hours=1"
  property_mappings       = local.oidc_scopes
  allowed_redirect_uris = [
    { matching_mode = "strict", redirect_uri_type = "authorization", url = "https://hermes.286k.co/auth/callback" },
    { matching_mode = "strict", redirect_uri_type = "authorization", url = "http://localhost:9119/auth/callback" },
  ]
}

resource "authentik_provider_oauth2" "level" {
  name                    = "Provider for Level"
  client_id               = "jTBLdMLCHu8Ai7CQcWbxLqmN1DjFek90xFtJUITp"
  client_type             = "public"
  authorization_flow      = data.authentik_flow.default_provider_authorization_implicit_consent.id
  invalidation_flow       = data.authentik_flow.default_provider_invalidation_flow.id
  signing_key             = data.authentik_certificate_key_pair.self_signed.id
  grant_types             = ["authorization_code", "implicit", "refresh_token", "client_credentials", "urn:ietf:params:oauth:grant-type:device_code"]
  sub_mode                = "hashed_user_id"
  access_token_validity   = "minutes=5"
  refresh_token_threshold = "hours=1"
  property_mappings       = local.oidc_scopes
  allowed_redirect_uris = [{
    matching_mode     = "strict"
    redirect_uri_type = "authorization"
    url               = "https://app.level.io/api/auth/sso/callback"
  }]
}

# UniFi directory sync / delegated auth. The outpost (ldap-home) runs on the home LAN,
# not in this cluster. Bind flow must stay ldap-authentication: the default flow's
# captcha stage breaks LDAP binds.
resource "authentik_provider_ldap" "unifi" {
  name             = "Provider for Unifi"
  base_dn          = "dc=ldap,dc=witl,dc=xyz"
  bind_flow        = authentik_flow.ldap_authentication.uuid
  unbind_flow      = data.authentik_flow.default_invalidation_flow.id
  bind_mode        = "cached"
  search_mode      = "cached"
  certificate      = data.authentik_certificate_key_pair.self_signed.id
  tls_server_name  = "10.2.30.217"
  mfa_support      = false
  uid_start_number = 2000
  gid_start_number = 4000
}
