---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-kiali
data:
  kiali.yaml: |
    version: 1
    metadata:
      name: kiali-oauth
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        id: kiali-provider
        state: present
        identifiers:
          name: Kiali
        attrs:
          name: Kiali
          client_type: confidential
          client_id: kiali
          redirect_uris:
            - matching_mode: strict
              url: https://kiali.cloud.witl.xyz/
            - matching_mode: strict
              url: https://kiali.cloud.witl.xyz
          sub_mode: user_email
          include_claims_in_id_token: true
          issuer_mode: per_provider
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      - model: authentik_core.application
        id: kiali-app
        state: present
        identifiers:
          slug: kiali
        attrs:
          name: Kiali
          slug: kiali
          policy_engine_mode: any
          provider: !KeyOf kiali-provider
