---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app postgres
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: barman-cloud
      namespace: cnpg-system
    - name: cert-manager
      namespace: cert-manager
    - name: onepassword-connect
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/database/cluster/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cloudflare-account-id-secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 10m
  wait: false
