---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-status-token
spec:
  # GitHub tokens expire after 60 minutes, refresh before that
  refreshInterval: "30m"
  target:
    name: github-status-token-secret
    template:
      data:
        token: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-access-token