---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mimir-read
spec:
  scaleTargetRef:
    name: mimir-read
    kind: Deployment
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://mimir-read.mimir-system.svc.cluster.local:8080/prometheus
        customHeaders: X-Scope-OrgID=witl-xyz
        query: sum(rate(cortex_request_duration_seconds_count{job="mimir-read"}[2m]))
        threshold: "50"
