---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: onepassword-secret
  data:
    - secretKey: 1password-credentials.json
      remoteRef:
        key: 1password
        property: OP_CREDENTIALS_JSON
    - secretKey: token
      remoteRef:
        key: 1password
        property: OP_CONNECT_TOKEN