---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: openid
    openid:
      client_id: "${client_id}"
      disable_rbac: true
      issuer_uri: "https://auth.cloud.witl.xyz/application/o/kiali/"
      scopes:
        - openid
        - profile
        - email
      username_claim: email
  deployment:
    cluster_wide_access: true
    view_only_mode: true
    accessible_namespaces:
      - "**"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 1Gi
  external_services:
    istio:
      root_namespace: istio-system
    prometheus:
      url: http://mimir-app.mimir-system.svc.cluster.local:8080/prometheus
      health_check_url: http://mimir-app.mimir-system.svc.cluster.local:8080/ready
      custom_headers:
        X-Scope-OrgID: "${mimir_org_id}"
    grafana:
      enabled: true
      internal_url: http://grafana-service.observability.svc.cluster.local:3000
      external_url: https://grafana.cloud.witl.xyz
      datasource_uid: prometheus
      auth:
        type: oauth2
        oauth2:
          client_id: "${grafana_m2m_client_id}"
          client_secret: "secret:kiali-grafana-oauth:client_secret"
          token_url: "https://auth.cloud.witl.xyz/application/o/token/"
          auth_style: header
      dashboards:
        - name: "Istio Service Dashboard"
          variables:
            datasource: "var-datasource"
            namespace: "var-namespace"
            service: "var-service"
        - name: "Istio Workload Dashboard"
          variables:
            datasource: "var-datasource"
            namespace: "var-namespace"
            workload: "var-workload"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
        - name: "Istio Wasm Extension Dashboard"
  server:
    web_fqdn: kiali.cloud.witl.xyz
    web_schema: https
    web_port: "443"
