---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-access-token
spec:
  appID: "${GITHUB_APP_ID}"
  installID: "${GITHUB_INSTALLATION_ID}"
  repositories:
    - cloud-ops
  permissions:
    contents: read
    statuses: write
  auth:
    privateKey:
      secretRef:
        name: github-status-app
        key: privateKey
