---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook
  mtls:
    mode: PERMISSIVE
