---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: cloudnative-pg-webhook
  namespace: cnpg-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  mtls:
    mode: PERMISSIVE
