---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./namespace.yaml
  - ./waypoint.yaml
  - ./waypoint-hpa.yaml
  - ./grafana/ks.yaml
  - ./loki/app
  - ./tempo/app
  - ./k8s-monitoring/secrets/ks.yaml
  - ./k8s-monitoring/ks.yaml
