---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kiali
    template:
      engineVersion: v2
      data:
        oidc-secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: kiali-oauth
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-oauth-client-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kiali-oauth-client-id
    template:
      engineVersion: v2
      data:
        client_id: "{{ .client_id }}"
  dataFrom:
    - extract:
        key: kiali-oauth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-mimir-org
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kiali-mimir-org
  data:
    - secretKey: mimir_org_id
      remoteRef:
        key: grafana-datasource-org
        property: org-id
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-grafana-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kiali-grafana-oauth
    template:
      engineVersion: v2
      data:
        client_secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: grafana-kiali-m2m
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-grafana-oauth-client-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kiali-grafana-oauth-client-id
    template:
      engineVersion: v2
      data:
        grafana_m2m_client_id: "{{ .client_id }}"
  dataFrom:
    - extract:
        key: grafana-kiali-m2m
