---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-r2-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tempo-r2-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_ENDPOINT: '{{ .s3_endpoint | replace "https://" "" | replace "http://" "" }}'
        S3_ACCESS_KEY_ID: '{{ .s3_access_key_id }}'
        S3_SECRET_ACCESS_KEY: '{{ .s3_secret_access_key }}'
        TEMPO_BUCKET_TRACES: '{{ .tempo_bucket_traces }}'
  dataFrom:
    - extract:
        key: tempo
