---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy-gateway
spec:
  compression:
    - type: Zstd
    - type: Gzip
  circuitBreaker:
    maxConnections: 1024
    maxPendingRequests: 512
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - gateway-error
        - connect-failure
        - reset
    perRetry:
      timeout: 5s
      backOff:
        baseInterval: 50ms
        maxInterval: 2s
  timeout:
    http:
      requestTimeout: 60s
      connectionIdleTimeout: 300s
      maxConnectionDuration: 3600s
    tcp:
      connectTimeout: 5s
  tcpKeepalive:
    idleTime: 60s
    interval: 10s
    probes: 3
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
