---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-gateway
spec:
  path:
    escapedSlashesAction: KeepUnchanged
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  connection:
    bufferLimit: 32Ki
    connectionLimit:
      value: 10000
      closeDelay: 5s
  timeout:
    http:
      requestReceivedTimeout: 60s
      idleTimeout: 300s
  tcpKeepalive:
    idleTime: 1200s
    interval: 60s
    probes: 3
  http2:
    onInvalidMessage: TerminateStream
    initialConnectionWindowSize: 1Mi
    initialStreamWindowSize: 64Ki
    maxConcurrentStreams: 100
  http3: {}
  tls:
    minVersion: "1.3"
    maxVersion: "1.3"
    alpnProtocols:
      - h3
      - h2
      - http/1.1
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
