---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        podDisruptionBudget:
          enabled: true
          maxUnavailable: 1
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.38.2
          resources:
            requests:
              cpu: "0.5"
              memory: 512Mi
            limits:
              memory: 2Gi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
      envoyService:
        externalTrafficPolicy: Local
      secretBackend:
        type: Kubernetes
  shutdown:
    drainTimeout: 180s
    enableShutdownGracePeriod: true
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Zstd
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gatewayclass_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy
  annotations:
    external-dns.alpha.kubernetes.io/target: external.cloud.witl.xyz
    gatus.home-operations.com/endpoint: |
      client:
        dns-resolver: tcp://1.1.1.1:53
      group: external
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: envoy.cloud.witl.xyz
      prometheus.io/scrape: "true"
      prometheus.io/port: "9901"
      prometheus.io/path: "/stats/prometheus"
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: cloud-witl-xyz-tls
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All