---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  install:
    crds: CreateReplace
  values:
    global:
      imageRegistry: mirror.gcr.io
    deployment:
      replicas: 2
      envoyGateway:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
    config:
      envoyGateway:
        extensionApis:
          enableBackend: true
        logging:
          level:
            default: info
        provider:
          type: Kubernetes
          kubernetes:
            deploy:
              type: GatewayNamespace
