---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway-helm
      version: "v1.8.1"
      sourceRef:
        kind: OCIRepository
        name: envoy-gateway
      interval: 3h
  install:
    crds: CreateReplace
  values:
    global:
      imageRegistry: mirror.gcr.io
    config:
      envoyGateway:
        extensionApis:
          enableBackend: true
        gateway:
          replicaCount: 2
        logging:
          level: info
        provider:
          type: Kubernetes
          kubernetes:
            deploy:
              type: GatewayNamespace
            resources:
              controller:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  memory: 512Mi