---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: istio
spec:
  gatewayClassName: istio
  infrastructure:
    annotations:
      load-balancer.hetzner.cloud/network-zone: eu-central
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "kiali.cloud.witl.xyz"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: cloud-witl-xyz-tls
    - name: tempo
      protocol: HTTPS
      port: 443
      hostname: "tempo.cloud.witl.xyz"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: cloud-witl-xyz-tls
