---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./gateway.yaml
  - ./gateway-authorizationpolicy.yaml
  - ./gateway-requestauthentication.yaml
  - ./serviceentry-gateway-hosts.yaml
