---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./gateway.yaml
  - ./gateway-requestauthentication.yaml
  - ./authorizationpolicies.yaml
  - ./envoyfilter-hardening.yaml
  - ./podmonitor.yaml
