---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/security.istio.io/authorizationpolicy_v1.json
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: tempo-jwt-required
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: istio
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts: ["tempo.cloud.witl.xyz"]
            paths: ["/ready*"]
    - to:
        - operation:
            hosts: ["tempo.cloud.witl.xyz"]
            paths: ["/api*"]
      when:
        - key: request.auth.claims[iss]
          values: ["https://auth.cloud.witl.xyz/application/o/grafana/"]
    - to:
        - operation:
            hosts: ["tempo.cloud.witl.xyz"]
            paths: ["/api*"]
      when:
        - key: request.auth.claims[scope]
          values: ["tempo:read"]
    - to:
        - operation:
            hosts: ["tempo.cloud.witl.xyz"]
            paths: ["/v1/traces*"]
      when:
        - key: request.auth.claims[scope]
          values: ["tempo:write"]
