---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kiali
spec:
  dependsOn:
    - name: kiali-operator
      namespace: istio-system
    - name: kiali-secrets
      namespace: istio-system
    - name: istio-ingress-gateway
      namespace: istio-ingress
    - name: mimir
      namespace: mimir-system
  interval: 1h
  path: ./kubernetes/apps/istio-system/kiali/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: kiali-oauth-client-id
      - kind: Secret
        name: kiali-mimir-org
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: istio-system
  wait: true
