---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
  mtls:
    mode: PERMISSIVE
