---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ambient-hostprobes.yaml
  - ./base-helmrelease.yaml
  - ./base-ocirepository.yaml
  - ./cni-helmrelease.yaml
  - ./cni-ocirepository.yaml
  - ./istiod-helmrelease.yaml
  - ./istiod-ocirepository.yaml
  - ./peerauthentication.yaml
  - ./servicemonitors.yaml
  - ./telemetry.yaml
  - ./ztunnel-helmrelease.yaml
  - ./ztunnel-ocirepository.yaml
