---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/telemetry.istio.io/telemetry_v1.json
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
        - name: envoy
  metrics:
    - providers:
        - name: prometheus
  tracing:
    - providers:
        - name: tempo
      randomSamplingPercentage: 10
